example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pyfb_endpoint.urls', namespace='pyfb_endpoint')),
]

pyfb_endpoint/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views


app_name = 'pyfb-endpoint'

router = routers.DefaultRouter()
router.register(r'customerendpoint', api.CustomerEndpointViewSet)
router.register(r'codec', api.CodecViewSet)
router.register(r'providerendpoint', api.ProviderEndpointViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for CustomerEndpoint
    path('pyfb_endpoint/customerendpoint/', views.CustomerEndpointListView.as_view(), name='pyfb_endpoint_customerendpoint_list'),
    path('pyfb_endpoint/customerendpoint/create/', views.CustomerEndpointCreateView.as_view(), name='pyfb_endpoint_customerendpoint_create'),
    path('pyfb_endpoint/customerendpoint/detail/<int:pk>/', views.CustomerEndpointDetailView.as_view(), name='pyfb_endpoint_customerendpoint_detail'),
    path('pyfb_endpoint/customerendpoint/update/<int:pk>/', views.CustomerEndpointUpdateView.as_view(), name='pyfb_endpoint_customerendpoint_update'),
)

urlpatterns += (
    # urls for Codec
    path('pyfb_endpoint/codec/', views.CodecListView.as_view(), name='pyfb_endpoint_codec_list'),
    path('pyfb_endpoint/codec/create/', views.CodecCreateView.as_view(), name='pyfb_endpoint_codec_create'),
    path('pyfb_endpoint/codec/detail/<int:pk>/', views.CodecDetailView.as_view(), name='pyfb_endpoint_codec_detail'),
    path('pyfb_endpoint/codec/update/<int:pk>/', views.CodecUpdateView.as_view(), name='pyfb_endpoint_codec_update'),
)

urlpatterns += (
    # urls for ProviderEndpoint
    path('pyfb_endpoint/providerendpoint/', views.ProviderEndpointListView.as_view(), name='pyfb_endpoint_providerendpoint_list'),
    path('pyfb_endpoint/providerendpoint/create/', views.ProviderEndpointCreateView.as_view(), name='pyfb_endpoint_providerendpoint_create'),
    path('pyfb_endpoint/providerendpoint/detail/<int:pk>/', views.ProviderEndpointDetailView.as_view(), name='pyfb_endpoint_providerendpoint_detail'),
    path('pyfb_endpoint/providerendpoint/update/<int:pk>/', views.ProviderEndpointUpdateView.as_view(), name='pyfb_endpoint_providerendpoint_update'),
)

pyfb_endpoint/models.py
# -*- coding: utf-8 -*-
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from netaddr import IPNetwork
import re
import random
import string

from model_utils.models import TimeStampedModel
from model_utils import Choices

from partial_index import PartialIndex

from pyfb_company.models import Customer, Provider

from pyfb_normalization.models import NormalizationGrp

from pyfb_kamailio.models import Domain, UacReg

from .validators import validate_cidr


def random_string():
    # Alphanumeric + special characters
    chars = string.ascii_letters + string.digits + string.punctuation

    pwdSize = 25

    return str(''.join((random.choice(chars)) for _ in range(pwdSize)))


class Codec(TimeStampedModel):

    # Fields
    name = models.CharField(_(u"name"), max_length=100, unique=True)
    number = models.PositiveIntegerField(_(u"payload number"), unique=True, help_text=_(u"payload types (PT) for audio encodings"))
    ptime = models.PositiveIntegerField(_(u"ptime"))
    stereo = models.BooleanField(_(u"is stereo ?"), default=False)
    rfc_name = models.CharField(_(u"rfc name"), max_length=30, unique=True, help_text=_(u"format is important !."))
    description = models.TextField(_(u"description"), blank=True, max_length=100)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('pyfb-endpoint:pyfb_endpoint_codec_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('pyfb-endpoint:pyfb_endpoint_codec_update', args=(self.pk,))


class CustomerEndpoint(TimeStampedModel):
    """ Customer Endpoint Model """

    # Choices
    SIP_TRANSPORT_CHOICES = Choices(
        'udp',
        'tcp',
        'tls'
    )
    RTP_TRANSPORT_CHOICES = Choices(
        'RTP/AVP',
    )
    TOS_RTP_CHOICES = Choices(
        # reference : https://en.wikipedia.org/wiki/Type_of_service
        (0, '0 - CS0 - 0 Best effort'),
        (160, '160 - CS5 - 5 Critical'),
        (184, '184 - EF - 5 Critical'),
    )

    # Fields
    name = models.CharField(_(u"username"), max_length=50, unique=True, help_text=_(u"Ex.: customer SIP username, etc..."))
    enabled = models.BooleanField(_(u"enabled / disabled"), default=True)
    registration = models.BooleanField(_(u"registration"), default=True, help_text=_(u"Is registration needed for calling ? True, the phone needs to register with correct username/password. If false, you must specify a CIDR in SIP IP CIDR !"))
    password = models.CharField(_(u"password"), max_length=64, blank=True, default=random_string, help_text=_(u"It's recommended to use strong passwords for the endpoint."))
    ha1 = models.CharField(_(u"ha1"), max_length=128, blank=True, default=random_string, help_text=_(u"It's recommended to use strong passwords for the endpoint. md5(username:realm:password)"))
    ha1b = models.CharField(_(u"ha1b"), max_length=128, blank=True, default=random_string, help_text=_(u"It's recommended to use strong passwords for the endpoint. md5(username@domain:realm:password)"))
    rtp_ip = models.CharField(_(u"RTP IP CIDR"), max_length=100, default="auto", help_text=_(u"Internal IP address/mask to bindto for RTP. Format : CIDR Ex. 192.168.1.0/32"))
    sip_ip = models.CharField(_(u"SIP IP CIDR"), max_length=100, null=True, blank=True, validators=[validate_cidr], help_text=_(u"Internal IP address/mask to bind to for SIP. Format : CIDR. Ex. 192.168.1.0/32"))
    sip_port = models.PositiveIntegerField(_(u"SIP port"), default=5060)
    sip_transport = models.CharField(_(u"SIP transport protocol"), max_length=15, default="udp", choices=SIP_TRANSPORT_CHOICES, help_text=_(u"Which transport protocol to use for SIP messages"))
    rtp_transport = models.CharField(_(u"RTP transport protocol"), max_length=15, default="RTP/AVP", choices=RTP_TRANSPORT_CHOICES, help_text=_(u"Which transport protocol to use for RTP packets"))
    rtp_tos = models.PositiveIntegerField(_(u"TOS value for RTP streams"), default=184, choices=TOS_RTP_CHOICES, help_text=_(u"Which TOS value to use for RTP packets"))
    max_calls = models.PositiveIntegerField(_(u'max calls'), default=1, help_text=_(u"max simultaneous calls allowed for this customer account."))
    calls_per_second = models.PositiveIntegerField(_(u'max calls per second'), default=10, help_text=_(u"maximum calls per second allowed for this customer endpoint."))
    outbound_caller_id_name = models.CharField(_(u"callerID name"), max_length=50, blank=True, help_text=_(u"Caller ID name sent to provider on outbound calls."))
    outbound_caller_id_number = models.CharField(_(u"callerID num"), max_length=80, blank=True, help_text=_(u"Caller ID number sent to provider on outbound calls."))
    force_caller_id = models.BooleanField(_(u"force callerID"), default=False)
    masq_caller_id = models.BooleanField(_(u"masq callerID"), default=False)
    pai = models.BooleanField(_(u"caller ID in PAI field"), default=False, help_text=_(u"put callerid in SIP P-Asserted-Id field if enabled"))
    pid = models.BooleanField(_(u"caller ID in PID field"), default=False, help_text=_(u"put callerid in SIP PID field if enabled"))
    ppi = models.BooleanField(_(u"caller ID in PPD field"), default=False, help_text=_(u"put callerid in SIP P-Preferred-Id field if enabled"))
    urgency_number = models.BooleanField(_(u"allow urgency numbers"), default=True, help_text=_(u"You have also to allow global routing option and define an urgency ratecard"))
    insee_code = models.CharField(_(u'special code for routing urgency numbers'), null=True, blank=True, max_length=10, help_text=_(u"Postal code, INSEE code ... for routing urgency number to the right urgency call center."))
    fake_ring = models.BooleanField(_(u"fake ring"), default=False, help_text=_(u"Fake ring : Enabled / Disabled - Send a fake ring to the caller."))
    cli_debug = models.BooleanField(_(u"CLI debug"), default=False, help_text=_(u"CLI debug : Enabled / Disabled - Permit to see all debug messages on cli."))
    transcoding_allowed = models.BooleanField(_(u'allow transcoding calls'), default=False, help_text=_(u"If enabled, calls could be transcoded. be careful, as it is an expensive cpu task."))
    recording_allowed = models.BooleanField(_(u'allow recording calls'), default=False, help_text=_(u"If enabled, calls could be recorded. be careful on available space."))
    recording_always = models.BooleanField(_(u'record all calls'), default=False, help_text=_(u"If enabled, all calls will be recorded. be careful on available space."))
    recording_limit = models.PositiveIntegerField(_(u'recording space storage'), default=30, help_text=_(u"how many Mo will be available for recording storage."))
    recording_retention = models.PositiveIntegerField(_(u'retention days for recording'), default=30, help_text=_(u"how many days a recording will be available. After, it will be deleted by automatic job"))
    description = models.TextField(_(u'description'), blank=True)

    # Relationship Fields
    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE, related_name="customers", verbose_name=_(u"customer")
    )
    callerid_norm = models.ForeignKey(
        NormalizationGrp,
        on_delete=models.CASCADE, related_name='calleridnormrules_c', null=True, blank=True, verbose_name=_(u"CallerID normalization rules for outbound call")
    )
    callee_norm = models.ForeignKey(
        NormalizationGrp,
        on_delete=models.CASCADE, related_name='caleenormrules_c', null=True, blank=True, verbose_name=_(u"Destination number normalization rules for outbound call")
    )
    callerid_norm_in = models.ForeignKey(
        NormalizationGrp,
        on_delete=models.CASCADE, related_name='calleridnormrulesin_c', null=True, blank=True, verbose_name=_(u"CallerID normalization rules for inbound call")
    )
    callee_norm_in = models.ForeignKey(
        NormalizationGrp,
        on_delete=models.CASCADE, related_name='caleenormrulesin_c', null=True, blank=True, verbose_name=_(u"Destination number normalization rules for inbound call")
    )
    domain = models.ForeignKey(
        Domain,
        on_delete=models.CASCADE, related_name='domain_edp', verbose_name=_(u"SIP Domain")
    )
    codec_list = models.ManyToManyField(
        Codec, blank=True,
        related_name="codecs_c",
        help_text=_(u"if NULL, all available codecs are allowed")
    )


    class Meta:
        db_table = 'pyfb_endpoint_customer'
        ordering = ('customer', 'name')
        verbose_name = _(u'customer endpoint')
        verbose_name_plural = _(u'customer endpoints')
        indexes = [
            PartialIndex(fields=['name', 'callerid_norm'], unique=True, where_postgresql='enabled = True'),
            PartialIndex(fields=['name', 'callee_norm'], unique=True, where_postgresql='enabled = True'),
            PartialIndex(fields=['name', 'callerid_norm_in'], unique=True, where_postgresql='enabled = True'),
            PartialIndex(fields=['name', 'callee_norm_in'], unique=True, where_postgresql='enabled = True'),
        ]

    def __str__(self):
        return "%s (%s:%s)" % (self.name, self.sip_ip, self.sip_port)

    def get_absolute_url(self):
        return reverse('pyfb-endpoint:pyfb_endpoint_customerendpoint_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('pyfb-endpoint:pyfb_endpoint_customerendpoint_update', args=(self.pk,))

    def clean(self):
        if (self.registration and
                (self.password is None or self.password == '')):
            raise ValidationError(_(u"""You have to specify a password if you
                                  want to allow registration"""))
        if (self.registration is False and
                (self.sip_ip is None or self.sip_ip == '')):

pyfb_endpoint/forms.py
from django import forms

from .models import CustomerEndpoint, Codec, ProviderEndpoint


class CustomerEndpointForm(forms.ModelForm):
    class Meta:
        model = CustomerEndpoint
        fields = ['registration', 'password', 'description', 'name', 'rtp_ip', 'sip_ip', 'sip_port', 'max_calls', 'calls_per_second', 'outbound_caller_id_name', 'outbound_caller_id_number', 'force_caller_id', 'masq_caller_id', 'urgency_number', 'insee_code', 'enabled', 'fake_ring', 'cli_debug', 'transcoding_allowed', 'recording_allowed', 'recording_always', 'recording_limit', 'recording_retention', 'sip_transport', 'rtp_transport', 'rtp_tos', 'pai', 'pid', 'ha1', 'ha1b', 'customer', 'callerid_norm', 'callee_norm', 'callerid_norm_in', 'callee_norm_in', 'codec_list']


class CodecForm(forms.ModelForm):
    class Meta:
        model = Codec
        fields = ['name', 'number', 'ptime', 'stereo', 'rfc_name', 'description']


class ProviderEndpointForm(forms.ModelForm):
    class Meta:
        model = ProviderEndpoint
        fields = ['name', 'max_calls', 'enabled', 'prefix', 'suffix', 'username', 'password', 'register', 'sip_proxy', 'sip_transport', 'sip_port', 'realm', 'from_domain', 'expire_seconds', 'retry_seconds', 'caller_id_in_from', 'pid', 'ppi', 'pai', 'calls_per_second', 'rtp_transport', 'rtp_tos', 'provider', 'add_plus_in_caller', 'callerid_norm', 'callee_norm', 'callerid_norm_in', 'callee_norm_in', 'codec_list']

pyfb_endpoint/views.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import CustomerEndpoint, Codec, ProviderEndpoint
from .forms import CustomerEndpointForm, CodecForm, ProviderEndpointForm


class CustomerEndpointListView(ListView):
    model = CustomerEndpoint


class CustomerEndpointCreateView(CreateView):
    model = CustomerEndpoint
    form_class = CustomerEndpointForm


class CustomerEndpointDetailView(DetailView):
    model = CustomerEndpoint


class CustomerEndpointUpdateView(UpdateView):
    model = CustomerEndpoint
    form_class = CustomerEndpointForm


class CodecListView(ListView):
    model = Codec


class CodecCreateView(CreateView):
    model = Codec
    form_class = CodecForm


class CodecDetailView(DetailView):
    model = Codec


class CodecUpdateView(UpdateView):
    model = Codec
    form_class = CodecForm


class ProviderEndpointListView(ListView):
    model = ProviderEndpoint


class ProviderEndpointCreateView(CreateView):
    model = ProviderEndpoint
    form_class = ProviderEndpointForm


class ProviderEndpointDetailView(DetailView):
    model = ProviderEndpoint


class ProviderEndpointUpdateView(UpdateView):
    model = ProviderEndpoint
    form_class = ProviderEndpointForm

pyfb_endpoint/templates/pyfb_endpoint/codec_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-endpoint:pyfb_endpoint_codec_list' %}">Codec Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
<tr><td>modified</td><td>{{ object.modified }}</td></tr>
<tr><td>number</td><td>{{ object.number }}</td></tr>
<tr><td>ptime</td><td>{{ object.ptime }}</td></tr>
<tr><td>stereo</td><td>{{ object.stereo }}</td></tr>
<tr><td>rfc_name</td><td>{{ object.rfc_name }}</td></tr>
<tr><td>description</td><td>{{ object.description }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Codec</a>

{% endblock %}

pyfb_endpoint/templates/pyfb_endpoint/codec_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-endpoint:pyfb_endpoint_codec_list' %}">Codec Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

pyfb_endpoint/templates/pyfb_endpoint/codec_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-endpoint:pyfb_endpoint_codec_list' %}">Codec Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>created</td>
    <td>modified</td>
    <td>number</td>
    <td>ptime</td>
    <td>stereo</td>
    <td>rfc_name</td>
    <td>description</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.modified }}</td>
    <td>{{ object.number }}</td>
    <td>{{ object.ptime }}</td>
    <td>{{ object.stereo }}</td>
    <td>{{ object.rfc_name }}</td>
    <td>{{ object.description }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-endpoint:pyfb_endpoint_codec_create' %}">Create new Codec</a>
{% endblock %}

pyfb_endpoint/templates/pyfb_endpoint/customerendpoint_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-endpoint:pyfb_endpoint_customerendpoint_list' %}">CustomerEndpoint Listing</a></p>
<table class="table">
<tr><td>registration</td><td>{{ object.registration }}</td></tr>
<tr><td>password</td><td>{{ object.password }}</td></tr>
<tr><td>description</td><td>{{ object.description }}</td></tr>
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>rtp_ip</td><td>{{ object.rtp_ip }}</td></tr>
<tr><td>sip_ip</td><td>{{ object.sip_ip }}</td></tr>
<tr><td>sip_port</td><td>{{ object.sip_port }}</td></tr>
<tr><td>max_calls</td><td>{{ object.max_calls }}</td></tr>
<tr><td>calls_per_second</td><td>{{ object.calls_per_second }}</td></tr>
<tr><td>outbound_caller_id_name</td><td>{{ object.outbound_caller_id_name }}</td></tr>
<tr><td>outbound_caller_id_number</td><td>{{ object.outbound_caller_id_number }}</td></tr>
<tr><td>force_caller_id</td><td>{{ object.force_caller_id }}</td></tr>
<tr><td>masq_caller_id</td><td>{{ object.masq_caller_id }}</td></tr>
<tr><td>urgency_number</td><td>{{ object.urgency_number }}</td></tr>
<tr><td>insee_code</td><td>{{ object.insee_code }}</td></tr>
<tr><td>enabled</td><td>{{ object.enabled }}</td></tr>
<tr><td>fake_ring</td><td>{{ object.fake_ring }}</td></tr>
<tr><td>cli_debug</td><td>{{ object.cli_debug }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
<tr><td>modified</td><td>{{ object.modified }}</td></tr>
<tr><td>transcoding_allowed</td><td>{{ object.transcoding_allowed }}</td></tr>
<tr><td>recording_allowed</td><td>{{ object.recording_allowed }}</td></tr>
<tr><td>recording_always</td><td>{{ object.recording_always }}</td></tr>
<tr><td>recording_limit</td><td>{{ object.recording_limit }}</td></tr>
<tr><td>recording_retention</td><td>{{ object.recording_retention }}</td></tr>
<tr><td>sip_transport</td><td>{{ object.sip_transport }}</td></tr>
<tr><td>rtp_transport</td><td>{{ object.rtp_transport }}</td></tr>
<tr><td>rtp_tos</td><td>{{ object.rtp_tos }}</td></tr>
<tr><td>pai</td><td>{{ object.pai }}</td></tr>
<tr><td>pid</td><td>{{ object.pid }}</td></tr>
<tr><td>ha1</td><td>{{ object.ha1 }}</td></tr>
<tr><td>ha1b</td><td>{{ object.ha1b }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit CustomerEndpoint</a>

{% endblock %}

pyfb_endpoint/templates/pyfb_endpoint/customerendpoint_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-endpoint:pyfb_endpoint_customerendpoint_list' %}">CustomerEndpoint Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>registration</td>
    <td>password</td>
    <td>description</td>
    <td>name</td>
    <td>rtp_ip</td>
    <td>sip_ip</td>
    <td>sip_port</td>
    <td>max_calls</td>
    <td>calls_per_second</td>
    <td>outbound_caller_id_name</td>
    <td>outbound_caller_id_number</td>
    <td>force_caller_id</td>
    <td>masq_caller_id</td>
    <td>urgency_number</td>
    <td>insee_code</td>
    <td>enabled</td>
    <td>fake_ring</td>
    <td>cli_debug</td>
    <td>created</td>
    <td>modified</td>
    <td>transcoding_allowed</td>
    <td>recording_allowed</td>
    <td>recording_always</td>
    <td>recording_limit</td>
    <td>recording_retention</td>
    <td>sip_transport</td>
    <td>rtp_transport</td>
    <td>rtp_tos</td>
    <td>pai</td>
    <td>pid</td>
    <td>ha1</td>
    <td>ha1b</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.registration }}</td>
    <td>{{ object.password }}</td>
    <td>{{ object.description }}</td>
    <td>{{ object.name }}</td>
    <td>{{ object.rtp_ip }}</td>
    <td>{{ object.sip_ip }}</td>
    <td>{{ object.sip_port }}</td>
    <td>{{ object.max_calls }}</td>
    <td>{{ object.calls_per_second }}</td>
    <td>{{ object.outbound_caller_id_name }}</td>
    <td>{{ object.outbound_caller_id_number }}</td>
    <td>{{ object.force_caller_id }}</td>
    <td>{{ object.masq_caller_id }}</td>
    <td>{{ object.urgency_number }}</td>
    <td>{{ object.insee_code }}</td>
    <td>{{ object.enabled }}</td>
    <td>{{ object.fake_ring }}</td>
    <td>{{ object.cli_debug }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.modified }}</td>
    <td>{{ object.transcoding_allowed }}</td>
    <td>{{ object.recording_allowed }}</td>
    <td>{{ object.recording_always }}</td>
    <td>{{ object.recording_limit }}</td>
    <td>{{ object.recording_retention }}</td>
    <td>{{ object.sip_transport }}</td>
    <td>{{ object.rtp_transport }}</td>
    <td>{{ object.rtp_tos }}</td>
    <td>{{ object.pai }}</td>
    <td>{{ object.pid }}</td>
    <td>{{ object.ha1 }}</td>
    <td>{{ object.ha1b }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-endpoint:pyfb_endpoint_customerendpoint_create' %}">Create new CustomerEndpoint</a>
{% endblock %}

pyfb_endpoint/templates/pyfb_endpoint/providerendpoint_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-endpoint:pyfb_endpoint_providerendpoint_list' %}">ProviderEndpoint Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>created</td>
    <td>modified</td>
    <td>max_calls</td>
    <td>enabled</td>
    <td>prefix</td>
    <td>suffix</td>
    <td>username</td>
    <td>password</td>
    <td>register</td>
    <td>sip_proxy</td>
    <td>sip_transport</td>
    <td>sip_port</td>
    <td>realm</td>
    <td>from_domain</td>
    <td>expire_seconds</td>
    <td>retry_seconds</td>
    <td>caller_id_in_from</td>
    <td>add_plus_in_caller</td>
    <td>pid</td>
    <td>pai</td>
    <td>calls_per_second</td>
    <td>rtp_transport</td>
    <td>rtp_tos</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.modified }}</td>
    <td>{{ object.max_calls }}</td>
    <td>{{ object.enabled }}</td>
    <td>{{ object.prefix }}</td>
    <td>{{ object.suffix }}</td>
    <td>{{ object.username }}</td>
    <td>{{ object.password }}</td>
    <td>{{ object.register }}</td>
    <td>{{ object.sip_proxy }}</td>
    <td>{{ object.sip_transport }}</td>
    <td>{{ object.sip_port }}</td>
    <td>{{ object.realm }}</td>
    <td>{{ object.from_domain }}</td>
    <td>{{ object.expire_seconds }}</td>
    <td>{{ object.retry_seconds }}</td>
    <td>{{ object.caller_id_in_from }}</td>
    <td>{{ object.add_plus_in_caller }}</td>
    <td>{{ object.pid }}</td>
    <td>{{ object.pai }}</td>
    <td>{{ object.calls_per_second }}</td>
    <td>{{ object.rtp_transport }}</td>
    <td>{{ object.rtp_tos }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-endpoint:pyfb_endpoint_providerendpoint_create' %}">Create new ProviderEndpoint</a>
{% endblock %}